"""Add AI analysis fields to content model

Revision ID: 0001_add_ai_analysis_fields
Revises: 
Create Date: 2025-08-21 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_add_ai_analysis_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('url', sa.String(), nullable=True))
    op.add_column('content', sa.Column('verification_score', sa.Float(), nullable=True))
    op.add_column('content', sa.Column('deepfake_probability', sa.Float(), nullable=True))
    op.add_column('content', sa.Column('verification_result', sa.Text(), nullable=True))
    op.add_column('content', sa.Column('deepfake_result', sa.Text(), nullable=True))
    op.add_column('content', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'uploaded_at')
    op.drop_column('content', 'deepfake_result')
    op.drop_column('content', 'verification_result')
    op.drop_column('content', 'deepfake_probability')
    op.drop_column('content', 'verification_score')
    op.drop_column('content', 'url')
    # ### end Alembic commands ###