name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/phase-4-enhancements ]
  pull_request:
    branches: [ main, feature/phase-4-enhancements ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pip install pytest pytest-asyncio
        python -m pytest src/tests/ -v --tb=short
    
    - name: Security scan
      run: |
        python -m pip install bandit
        bandit -r src/ -ll
    
    - name: Linting
      run: |
        python -m pip install flake8
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Dependency analysis
      run: |
        python -m pip install safety pip-audit
        safety check -r requirements.txt
        pip-audit -r requirements.txt