name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/phase-4-enhancements ]
  pull_request:
    branches: [ main, feature/phase-4-enhancements ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Install Dagger
      run: |
        mkdir -p $HOME/bin
        cd $HOME/bin
        wget -O dagger.tar.gz "https://github.com/dagger/dagger/releases/download/v0.18.16/dagger_v0.18.16_linux_amd64.tar.gz"
        tar xzf dagger.tar.gz
        chmod +x dagger
        echo "$HOME/bin" >> $GITHUB_PATH
    
    - name: Test Dagger installation
      run: |
        dagger version